//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motivational.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motivational.Localizations.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause current period.
        /// </summary>
        public static string app_button_pause_title {
            get {
                return ResourceManager.GetString("app_button_pause_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show settings.
        /// </summary>
        public static string app_button_settings {
            get {
                return ResourceManager.GetString("app_button_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start period.
        /// </summary>
        public static string app_button_start_title {
            get {
                return ResourceManager.GetString("app_button_start_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all sessions and start from the beginning.
        /// </summary>
        public static string app_button_stop_title {
            get {
                return ResourceManager.GetString("app_button_stop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        public static string app_button_window_close {
            get {
                return ResourceManager.GetString("app_button_window_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize window.
        /// </summary>
        public static string app_button_window_minimize {
            get {
                return ResourceManager.GetString("app_button_window_minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string app_jumplist_item_pause {
            get {
                return ResourceManager.GetString("app_jumplist_item_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause current Pomodoro session.
        /// </summary>
        public static string app_jumplist_item_pause_title {
            get {
                return ResourceManager.GetString("app_jumplist_item_pause_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string app_jumplist_item_reset {
            get {
                return ResourceManager.GetString("app_jumplist_item_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset sessions and start from the beginning.
        /// </summary>
        public static string app_jumplist_item_reset_title {
            get {
                return ResourceManager.GetString("app_jumplist_item_reset_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string app_jumplist_item_restart {
            get {
                return ResourceManager.GetString("app_jumplist_item_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart current Pomodoro session.
        /// </summary>
        public static string app_jumplist_item_restart_title {
            get {
                return ResourceManager.GetString("app_jumplist_item_restart_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string app_jumplist_item_settings {
            get {
                return ResourceManager.GetString("app_jumplist_item_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display application settings.
        /// </summary>
        public static string app_jumplist_item_settings_title {
            get {
                return ResourceManager.GetString("app_jumplist_item_settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string app_jumplist_item_start {
            get {
                return ResourceManager.GetString("app_jumplist_item_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pomodoro session.
        /// </summary>
        public static string app_jumplist_item_start_title {
            get {
                return ResourceManager.GetString("app_jumplist_item_start_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel running pomodoro session and exit application?.
        /// </summary>
        public static string app_message_confirm_exit {
            get {
                return ResourceManager.GetString("app_message_confirm_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reset number of Pomodoro sessions and start over?.
        /// </summary>
        public static string app_message_confirm_session_reset {
            get {
                return ResourceManager.GetString("app_message_confirm_session_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurray, you&apos;ve got whole {0} minutes to rest! Go for a walk!.
        /// </summary>
        public static string app_period_long_break_caption {
            get {
                return ResourceManager.GetString("app_period_long_break_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press play to start earned {0} minutes long break.
        /// </summary>
        public static string app_period_motivation_start_long_break {
            get {
                return ResourceManager.GetString("app_period_motivation_start_long_break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press play to start your new challenge.
        /// </summary>
        public static string app_period_motivation_start_pomodoro {
            get {
                return ResourceManager.GetString("app_period_motivation_start_pomodoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press play to start your {0} minutes break.
        /// </summary>
        public static string app_period_motivation_start_short_break {
            get {
                return ResourceManager.GetString("app_period_motivation_start_short_break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shouldn&apos;t you be focused already? Stop staring on this window and let&apos;s get some things done..
        /// </summary>
        public static string app_period_pomodoro_caption_default {
            get {
                return ResourceManager.GetString("app_period_pomodoro_caption_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press play to start new period.
        /// </summary>
        public static string app_period_press_play_to_start {
            get {
                return ResourceManager.GetString("app_period_press_play_to_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve got {0} minutes to rest. Let&apos;s do some stretching..
        /// </summary>
        public static string app_period_short_break_caption {
            get {
                return ResourceManager.GetString("app_period_short_break_caption", resourceCulture);
            }
        }
    }
}
